runmode: debug               # 开发模式, debug, release, test
addr: :8001                  # HTTP绑定端口
name: apiserver              # API Server的名字
url: http://127.0.0.1:8001  # pingServer函数请求的API服务器的ip:port
max_ping_count: 10           # pingServer函数try的次数
worker:
  queue_size: 3000
  max_worker_num:  100
login:
  timeoutperiod: 1800
db:
  name: funnyvotego 
  addr: localhost 
  username: root
  password: 123 
  
